version: "2"
services:
  api:
    build: .
    ports:
      - "3000:3000"
      # - 9229:9229
    depends_on:
      - postgres
    environment:
      DB_URI: "postgres://postgres:P@ssword123@postgres:5432/postgres"
    command: 
      - node
      - "dist/server.js"
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: P@ssword123
    ports:
      - "5432:5432"